### ISSUE TITLE
Use Easy* lists directly and add all four of them to default subscriptions

### ISSUE THREAD

**Issue by saurabhdua82** [binoc-central/abprime#1]
Hello!

Using the latest version of this extension on the latest version of PaleMoon web browser.
"Add filter subscription" isn't leading to >> 'Easy-privacy' & similarly 'Add a different subscription' has no choice on it as well !?

Therefore, how do we add "Easy Privacy" to our current list of subscriptions ?
Inputs will be greatly appreciated.
Thank you.

**Comment by mattatobin** [comment]
I am gonna stop using Adblock Plus's versions of EasyList and set the ones you can easily select from the dropdown to use the real ones from https://easylist.to/ directly.
