### ISSUE TITLE
ABPrime: import lists from uBlock Origin

### ISSUE THREAD

**Issue by laozi83** [binoc-central/abprime#2]
hello,
I have been using uBloc Origin for a few years but I am very interested in ABPrime,
my use with uBlock:

Filter list tab:
-uBlock filters - Resource abuse
-NoCoin Filter List (personal list)
no other list is selected

tab my filters:
295 aesthetic filters that I made myself

dynamic filtering tab:
439 filters

questions:
how to insert all these filters in ABprime?
is that possible ?

thank you for your lighting

**Comment by mattatobin** [comment]
I'd have to see the filters. While uBlock can use Adblock style filterlists i have no idea if it internally uses the same syntax.

**Comment by laozi83** [comment]
here is an example of filters:

**my filters**: (i voluntarily deleted the prefix www. )
frandroid.com##.oopnative
frandroid.com###trending-bar
francetvinfo.fr###newsletterSubContainer
boulanger.com##.owl-wrapper-outer
||boulanger.com/*/*/*/*.jpg$image
anfr.fr##.carousel-content
anfr.fr##.clearfix.entete-container
anfr.fr##.clearfix.wrapper-container
anfr.fr##.clearfix.bloc-reseaux-sociaux
forums.mozfr.org##.login-title
gratilog.net##.txtcenter > a[href="http://www.gratilog.net/xoops/register.php"]
meteofrance.com##[id^=article_]

**dynamic filtering**: (instead of the black dot in front of the filter is * )
* 0914.global.ssl.fastly.net * block
* 146.148.126.242 * block
* 247realmedia.com * block
* 3lift.com * block
* abtasty.com * block
* accounts.google.com * block
* achetezfacile.com * block
* addthis.com * block
* adleadevent.com * block
* adnext.fr * block
* adnxs.com * block
* adobedtm.com * block

**Comment by mattatobin** [comment]
I don't think your dynamic filters will work.. the others.. not sure about the one with ^ in it.. but the rest SHOULD work.

See, Adblock Plus's filter synatx.. It is pretty close to what ABPrime uses.

**Comment by laozi83** [comment]
thanks for the info, subject to closing.
