### ISSUE TITLE
4chan.org behaving badly (ruled out Pale Moon and EasyList)

### ISSUE THREAD

**Issue by BenFenner** [binoc-central/abprime#5]
I've done a good bit of testing and finally believe the ABPrime extension is the source of this bug.
A few weeks back I've noticed the frames version of 4chan not working at all.
https://4chan.org/frames (NSFW)

It displays a white frame on the left, and a white frame on the right, both about equal width.
Viewing the source shows the content is missing, and likely a JS fill problem. The console shows no JS errors (no errors of any kind actually).
Screenshot: https://i.imgur.com/utineYr.png

If I visit https://4chan.org without the frames, the site redirects to the frames site with the same results.

If I visit a board directly without frames https://4chan.org/o (SFW automotive section) then the site seems to work normally (albeit without frames) except many of the thumbnails, when clicked, won't load the larger image, and instead a user-friendly 404 notice is displayed at the top of the screen.
Screenshot: https://i.imgur.com/g8slPid.png

I have confirmed this on multiple machines. The problem exists on any Pale Moon setup with ABPrime installed and EasyList active. Disabling the ad blocking specifically for the 4chan domain allows the site to work properly. Disabling EasyList entirely allows the site to work properly. Uninstalling ABPrime allows the site to work properly.
I have been testing with ABPrime 1.0.5 but noticed 1.0.6 came out just today, so I tested with that too and am seeing the same problem.

The issue doesn't seem to be with EasyList though, as I've confirmed 4chan works fine with Firefox portable and uBlock Origin (EasyList enabled) and then went even further and tried a Pale Moon setup with AdBlock Latitude (EasyList enabled) which also worked fine. It really seems that ABPrime is the culprit here.

Let me know if I can provide any more information.

Here is the initial Pale Moon bug report:
https://forum.palemoon.org/viewtopic.php?f=29&t=18789&p=142629#p142606

Here is the initial EasyList bug report:
https://forums.lanik.us/viewtopic.php?f=64&t=40926

**Comment by mattatobin** [comment]
I already fixed it.. As noted, elsewhere, ABPrime currently isn't very tolerant of unknown filters..

**Comment by BenFenner** [comment]
Any idea what version release this is fixed in, or any tips finding the specific commit? I'm a bit curious as to what it was.
And what does ABPrime consider known filters? I'm a little foggy there...

**Comment by BenFenner** [comment]
Excellent work, thank you!
