### ISSUE TITLE
Show in status bar is broken

### ISSUE THREAD

**Issue by SpockMan02** [binoc-central/abprime#6]
ABPrime 1.0.7, Pale Moon 27.9.0, macOS 10.12.6 and Windows 7.

STR: Click ABPrime button in the status bar, check `Show in status bar`.

Results: When this is checked, there are two ABPrime buttons in the status bar, identical in functionality, but one of which lacks a menu-indicating downward arrow and hover effect. When `Show in status bar` is unchecked, one (fully functional) ABPrime button remains in the status bar.

Expected: Only one ABPrime button should be in the status bar at a time, or none when `Show in status bar` is unchecked.

Edit: Hm, it turns out this just happens because I had the button with the arrow dragged into the status bar, but everything makes sense when it's in the nav bar. I'm not sure if this is a bug or not; maybe you should disable `Show in status bar` when it's already in the status bar, but that's up to you.

**Comment by mattatobin** [comment]
There is a difference between the toolbar button and the status bar icon but maybe they should be mutually exclusive on applications WITH status bar capabilities.

Toolbar button OR Status Bar icon.

**Comment by SpockMan02** [comment]
Alright, cool, I apologize for reporting a non-issue. :)
